global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']










  # - job_name: 
  #   metrics_path: /metrics
  #   honor_labels: false
  #   honor_timestamps: true
  #   scheme: http
  #   follow_redirects: true
  #   body_size_limit: "0"
  #   sample_limit: 0
  #   label_limit: 0
  #   label_name_length_limit: 0
  #   label_value_length_limit: 0
  #   target_limit: 0